### ISSUE TITLE
Publish to hackage

### ISSUE THREAD

**Issue by corpix** [freylax/hakyll-dir-list#2]
Hello, do you have any plans on publishing it to hackage?

**Comment by freylax** [comment]
I have not thought about it yet, but if it makes sense to you, why not.
Do you use this package?

best regards
Robert

**Comment by corpix** [comment]
I have tried it, but it works with older version of hakyll than I use... so I decided not to use it until I have time to fix compilation errors :)

**Comment by freylax** [comment]
I published the package on hackage now,
compiles with hakyll 4.11
